source 'https://rubygems.org'
gem 'jekyll-gist', '1.1.0'
gem 'rdiscount'
gem 'kramdown'
gem 'sass'
gem 'nokogiri'
gem 's3_website'
gem 'html-proofer'
gem 'faraday'
gem 'jekyll-redirect-from'
gem 'liquid-rails', '~> 0.1.0'
gem 'documentation', '~> 1.0', '>= 1.0.9'
gem 'branch_io', '~> 0.1.0'
gem 'rubygems-update', '~> 2.6', '>= 2.6.12'
