source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-gist', '1.1.0'
gem 'rdiscount'
gem 'kramdown'
gem 'sass'
gem 'nokogiri'
gem 's3_website'
gem 'html-proofer'
gem 'faraday'
gem 'jekyll-redirect-from', '~> 0.9.0'
gem 'liquid-rails'
gem 'documentation', '~> 1.0', '>= 1.0.9'
gem 'branch_io', '~> 0.1.0'
gem 'rubygems-update', '~> 2.6', '>= 2.6.12'
gem 'pry', '~> 0.10.4'
gem 'puts_debuggerer', '~> 0.5.0'
